### ISSUE TITLE
mif missing lines

### ISSUE THREAD

**Issue by gdalyh** [makigumo/bin2mif#1]
when a set of equal values are at the end of the bin file, they are not written to the mif file.

proposal for a solution:

after the except instead of pass, write as in line 87 and "i+1" instead "i". 

    except BinaryEOFException:
      fh.write(f"  [{pos_start:04X}..{i+1:04X}]  :   {new_byte_value:02X};\n")

**Comment by makigumo** [comment]
Thank you for your report and proposal.
I went about it a little different, but I think this issue is now fixed (7df2818). Would be nice if you could test and report back.

**Comment by gdalyh** [comment]
Thanks, good work.
